apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: herdeybayor/ticketing_auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*
